# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_companysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text=b'Percentage as fraction, e.g. 15\\%\\ Tax Rate would be 0.15', max_digits=4),
        ),
    ]
