# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 19:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_company_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='payment_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='companygroup',
            name='permissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
