# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 14:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_ipstore_geocoded_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipstore',
            name='profile',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
