# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_auto_20160223_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='matric_name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='matric_unit',
        ),
    ]
