# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_plan_modules_planmodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='segment',
            field=models.IntegerField(choices=[(0, b'Core'), (1, b'Data Management Platform'), (2, b'Reporting')], default=0),
        ),
    ]
