# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_added_plan_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text=b'The name of the module', max_length=128),
        ),
        migrations.AlterField(
            model_name='module',
            name='segment',
            field=models.IntegerField(choices=[(0, b'Core'), (1, b'Data Management Platform'), (2, b'Reporting')], default=0, help_text=b'The segment it is part of'),
        ),
    ]
