# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 18:32
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_auto_default_currency_USD'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, null=True),
        ),
    ]
