# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_plan_stripe_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['amount']},
        ),
    ]
